### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by ghost** [jiupinjia/SkyAR#1]
can you please add a google colab for inference thanks

**Comment by jiupinjia** [comment]
> can you please add a google colab for inference thanks

Hi, the link to the colab runtime has been added. Thanks for your suggestion.

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
@jiupinjia I am getting this error for the last cell in colab

AttributeError                            Traceback (most recent call last)
<ipython-input-11-fb48df0dcfce> in <module>()
     10 fig = plt.figure(figsize=(4,8))
     11 plt.axis('off')
---> 12 fig.axes.get_yaxis().set_visible(False)
     13 ims = [[plt.imshow(img[:,:,::-1], animated=True)] for img in sf.output_img_list[0:40]]
     14 ani = animation.ArtistAnimation(fig, ims, interval=50)

AttributeError: 'list' object has no attribute 'get_yaxis'

**Comment by jiupinjia** [comment]
You can remove the line "plt.axis('off')" and try again.
Actually, when you have reached the last cell, the results are already there in the ./SkyAR folder. The last cell is only used for a previous of your results.

**Comment by jiupinjia** [comment]
previous --> preview, sorry
