### ISSUE TITLE
Input Error

### ISSUE THREAD

**Issue by will0000000** [jiupinjia/SkyAR#13]
I have a problem while runniing the project. there is a ./torch folder under my c drive.but my other programs are under F,i dont know if it has anything with it.  :(

![QQ截图20201125130131](https://user-images.githubusercontent.com/69883633/100185297-7564d980-2f1e-11eb-8971-74adc98bd18f.png)

**Comment by jiupinjia** [comment]
Hi @will0000000, which version of PyTorch are you using? Can you try switching the mode 'bicubic' of line 83 in skymagic.py to 'bilinear'? Tell me whether it works fine. Thank you.

**Comment by will0000000** [comment]
非常非常抱歉我来晚了，同时非常感谢你的回复。我在这个环境中使用的是pytorch1.0.0，我把bicubic改成bilinear后它可以顺利运行了。但是它好像卡在了最后一步，我怀疑是我电脑配置的原因。
![QQ截图20201206110453](https://user-images.githubusercontent.com/69883633/101270335-e88a0d80-37b2-11eb-9234-98b575850b9e.png)

**Comment by jiupinjia** [comment]
Hi @will0000000, it seems your video has been processed successfully. You can check out your repo dir and see if there is a demo.mp4 result file. BTW, I also notice that there might be another problem that your sky area is too small, as shown in your command window.

**Comment by will0000000** [comment]
啊哈哈我知道了。非常感谢你！现在没有任何问题了。

**Comment by jiupinjia** [comment]
Cheers!
