### ISSUE TITLE
I can only generate the 40frame GIF previews in Colab

### ISSUE THREAD

**Issue by croze97** [jiupinjia/SkyAR#14]
Running through the Google Colab notebook, Wandb only seems to contain GIF outputs for my videos. The notebook says I can download a full video rather than the preview at /SkyAR/demo.avi but I see no AVI files in my Wandb media. What am I missing here?

**Comment by jiupinjia** [comment]
Hi @croze97, are u running the Colab demo attached in this repository or another one on Wandb.ai?

**Comment by croze97** [comment]
I'm sorry, I feel really dumb... The .avi video is located in the Google Colab file directory on the left-hand side, not Wandb. Closing this one out, thanks for the super quick response!

**Comment by jiupinjia** [comment]
You're good! Thank you all the same for your feedback.
