### ISSUE TITLE
how to save the videos

### ISSUE THREAD

**Issue by gearless-c-Joe** [jiupinjia/SkyAR#16]
After processing the image and videos, there is no mp4 in the "jpg_output".
So , how to save the result.
please

**Comment by jiupinjia** [comment]
Hi @gearless-c-Joe, you can find the video results "demo.mp4" and "demo-cat.mp4" directly at the repo directory.

**Comment by jiupinjia** [comment]
Hi @gearless-c-Joe, maybe I didn't explain it clearly. Suppose you are working at the directory "./SkyAR". The results are right at "./SkyAR/demo.mp4" and "./SkyAR/demo-cat.mp4". There will be no video results in the "./SkyAR/jpg_output" folder.

**Comment by gearless-c-Joe** [comment]
> Hi @gearless-c-Joe, maybe I didn't explain it clearly. Suppose you are working at the directory "./SkyAR". The results are right at "./SkyAR/demo.mp4" and "./SkyAR/demo-cat.mp4". There will be no video results in the "./SkyAR/jpg_output" folder.

i find it ! thank you very much!
