### ISSUE TITLE
Question regarding CoordConv

### ISSUE THREAD

**Issue by yggs1401** [jiupinjia/SkyAR#20]
Hello,

First of all, nice job. I was wondering why did you only encode the y coordinate for the CoordConv instead of both x, y or only x. Can you explain the reason behind this?

Thank you!

**Comment by jiupinjia** [comment]
Hi @yggs1401, thanks for your question. The reason why I was only using y instead of using (x, y) is that sky pixels usually appear in the upper region of an image. There is no clear clue as to which part of the sky tends to appear in the x-direction.

**Comment by yggs1401** [comment]
Thank you for your answer! From upper region I need to understand the y-axis related to the height of the image and thus we locate the sky region?

**Comment by jiupinjia** [comment]
Yes, exactly. The pixels at the top of the image are more likely to be sky pixels than the pixels at the bottom.

**Comment by yggs1401** [comment]
I understand now, thank you! I will close the issue now
