### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by QIANSUIMINGMINGMING** [jiupinjia/SkyAR#21]
`from skimage.measure import compare_ssim as sk_cpt_ssim` in utils.py
import problems: **ImportError**: cannot import name 'compare_ssim' from 'skimage.measure' (D:\anaconda\envs\pytorch\lib\site-packages\skimage\measure\__init__.py)
I find that the latest version of scikit-image doesn't have "compare_ssim".
Maybe an update in requirements.txt is needed

**Comment by yeshunlong** [comment]
using `pip3 install scikit-image` can install it

**Comment by QIANSUIMINGMINGMING** [comment]
Maybe I should make it more clear, the latest version of scikit-image, which might be 0.18.2 or others, doesn’t have compare_ssim. I finally uninstalled this version and used `pip install scikit-image==0.15.0` to install a older version and fixed this problem.
The Requirements.txt doesn’t mention the version of scikit-image.
