### ISSUE TITLE
Can't install Requirements.txt

### ISSUE THREAD

**Issue by LWJerri** [jiupinjia/SkyAR#5]
Hello! I have a problem with installing Requirements.txt. I can't correctly install modules and every time gets an error.

- scipy send `No lapack/blas resources found.` and other libraries. Can you send a list of all commands for pretty installing?
To install all modules I'm using `pip install Requirements.txt`.

**Comment by cql1983** [comment]
I use `pip3 install -r Requirements.txt`  ,install is correct .

**Comment by jiupinjia** [comment]
> Hello! I have a problem with installing Requirements.txt. I can't correctly install modules and every time gets an error.
> 
> * scipy send `No lapack/blas resources found.` and other libraries. Can you send a list of all commands for pretty installing?
>   To install all modules I'm using `pip install Requirements.txt`.

Hi, sorry for the late reply. What system are you using? Also, can you show me a more detailed error report?

**Comment by LWJerri** [comment]
> > Hello! I have a problem with installing Requirements.txt. I can't correctly install modules and every time gets an error.
> > 
> > * scipy send `No lapack/blas resources found.` and other libraries. Can you send a list of all commands for pretty installing?
> >   To install all modules I'm using `pip install Requirements.txt`.
> 
> Hi, sorry for the late reply. What system are you using? Also, can you show me a more detailed error report?

I'm using Windows 10.

![image](https://user-images.githubusercontent.com/50290430/97718782-5fa6f480-1ad7-11eb-8b73-d0fd974e2ce3.png)
![image](https://user-images.githubusercontent.com/50290430/97718830-6afa2000-1ad7-11eb-97e6-d0bee4266892.png)

**Comment by jiupinjia** [comment]
I am still trying to figure out what is behind your problem. If there is any progress, I will give you feedback in time. I have created a [Colab runtime](https://colab.research.google.com/drive/1-BqXD3EzDY6PHRdwb3cWayk2KictbFaz?usp=sharing) that you can test where the dependencies are already installed. You can try on the colab first if you want.

**Comment by getbirra** [comment]
> > > Hello! I have a problem with installing Requirements.txt. I can't correctly install modules and every time gets an error.
> > > 
> > > * scipy send `No lapack/blas resources found.` and other libraries. Can you send a list of all commands for pretty installing?
> > >   To install all modules I'm using `pip install Requirements.txt`.
> > 
> > 
> > Hi, sorry for the late reply. What system are you using? Also, can you show me a more detailed error report?
> 
> I'm using Windows 10.
> 
> ![image](https://user-images.githubusercontent.com/50290430/97718782-5fa6f480-1ad7-11eb-8b73-d0fd974e2ce3.png)
> ![image](https://user-images.githubusercontent.com/50290430/97718830-6afa2000-1ad7-11eb-97e6-d0bee4266892.png)

This works with anaconda in windows 10.

**Comment by jiupinjia** [comment]
> I'm using Windows 10.
> 
Can you try to install anaconda first? 
Also, thank getbirra for his/her suggestion.

**Comment by LWJerri** [comment]
> > I'm using Windows 10.
> 
> Can you try to install anaconda first?
> Also, thank getbirra for his/her suggestion.

Okay, thanks.

**Comment by jiupinjia** [comment]
Hi @LWJerri, have you solved your installation problem? I'm closing this issue. Please feel free to reach out to me if you have any further problems.

**Comment by LWJerri** [comment]
> Hi @LWJerri, have you solved your installation problem? I'm closing this issue. Please feel free to reach out to me if you have any further problems.

My problem isn't solved.

**Comment by jiupinjia** [comment]
@LWJerri, have you tried to install anaconda first?

**Comment by LWJerri** [comment]
> @LWJerri, have you tried to install anaconda first?

No. I wanna run this code on Windows 10.

**Comment by jiupinjia** [comment]
That's where the problem is - you will need to install anaconda on your windows 10 machine first. No matter where we run the code - windows, Linux, or Mac, we all need anaconda installed first.

**Comment by LWJerri** [comment]
> That's where the problem is - you will need to install anaconda on your windows 10 machine first. No matter where we run the code - windows, Linux, or Mac, we all need anaconda installed first.

Hmm, okay, thanks!
