### ISSUE TITLE
请问能帮忙把预训练模型放一放在百度网盘吗，国内上不了google网盘

### ISSUE THREAD

**Issue by bfdong** [jiupinjia/SkyAR#8]

**Comment by jiupinjia** [comment]
Hi, you can download the checkpoint from the following

https://pan.baidu.com/s/1sjwSRmqswFaOXb7xbHKNVA
(Key: jack)

Also, I would like to thank Jack Cui for his help. 
https://mp.weixin.qq.com/s/bUVvafODJfqDHXWXhDxVhA

**Comment by jiupinjia** [comment]
I am closing this issue. Please feel free to contact me if you have any further questions.
